<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["booking/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["booking/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Booking Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Member Name</th>
            <th>Trainer Name</th>
            <th>Fee</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $booking): ?>
            <tr>
                <td><?php echo $booking->getId() ?></td>
            <td><?php echo $booking->getBookingdate() ?></td>
            <td><?php echo $booking->getStarttime() ?></td>
            <td><?php echo $booking->getEndtime() ?></td>
            <td><?php echo $booking->getmember() ?></td>
            <td><?php echo $booking->getTrainer() ?></td>
            <td><?php echo $booking->getFee() ?></td>

                <td><?php echo $this->tag->linkTo(["booking/edit/" . $booking->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["booking/delete/" . $booking->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("booking/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("booking/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("booking/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("booking/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
